package alfheim.common.network

enum class M0dc { MTSPELL, ROLL, SEEME, SSS }

enum class M0ds { AKASHIK_SCROLL_UP, AKASHIK_SCROLL_DOWN, DODGE, HEIMBLINK, JUMP }

enum class M1d { COLD, DEATH_TIMER, ELVEN_FLIGHT_MAX, ESMABIL, GINNUNGAGAP, KNOWLEDGE, LIMBO, NOSUNMOON, RAGNAROK, RLCM, TIME_STOP_REMOVE }

enum class M1l { SEED }

enum class M2d { PARTYID, COOLDOWN, ATTRIBUTE, MODES, FIREBALLSYNC, PRIOTGT }

enum class M3d { PARTY_STATUS, KEY_BIND, WEATHER, TOGGLER }

enum class Mni { BLIZZARD, HEARTLOSS, INTERACTION, WINGS_BL }
